### ISSUE TITLE
Image without width and height impacting performance

### ISSUE THREAD

**Issue by mchv** [guardian/thrashers#173]
<img width="924" alt="Screenshot 2021-03-05 at 11 27 26" src="https://user-images.githubusercontent.com/615085/110109830-e29dcb80-7da5-11eb-8d15-a049902c5df6.png">

@HarryFischer Could you fix this please? an `alt` will be good as well
@jfsoul @paperboyo we could probably add a linter to detect such kind of issues as well as accessibility issues. 
On the longer term when we redesign front we should likely rely on `image-rendering`

**Comment by HarryFischer** [comment]
@mchv That's done now

**Comment by mchv** [comment]
@HarryFischer  While I can see the `alt` change I am not seeing `width` and `height` [being added.](url)
<img width="799" alt="Screenshot 2021-03-08 at 12 23 34" src="https://user-images.githubusercontent.com/615085/110322168-9901ea80-800a-11eb-96bc-ae3ea51d2ed0.png">

**Comment by HarryFischer** [comment]
Sorry - have added now:
![Screenshot 2021-03-09 at 10 24 34](https://user-images.githubusercontent.com/20658471/110456741-d2e1f800-80c1-11eb-943a-59c14ee91f5c.png)

**Comment by mchv** [comment]
Thanks!
